### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wangyu0627** [LehengTHU/AlphaRec#3]
Hello, great job! May I ask when are you going to open source all the datasets, I can't wait to Ffollow this job.

**Comment by wangyu0627** [comment]
And, the embedding dimension is different for each LLM output, how do you compare.

**Comment by LehengTHU** [comment]
> And, the embedding dimension is different for each LLM output, how do you compare.

Thanks for your interest. In the linear mapping experiment, we only use a linear matrix of the same output dimension. In the AlphaRec setting, we adjust the hidden layer of the MLP to ensure a similar parameter size for different language representations.

**Comment by LehengTHU** [comment]
> Hello, great job! May I ask when are you going to open source all the datasets, I can't wait to Ffollow this job.

Thanks for your interest. Maybe I will release them this week when I am available.

**Comment by LehengTHU** [comment]
> Hello, great job! May I ask when are you going to open source all the datasets, I can't wait to Ffollow this job.

Hello. All the datasets have been uploaded.

**Comment by wangyu0627** [comment]
Thank you for your contribution~！

**Comment by trannhuthuat96** [comment]
Hello @LehengTHU 

Thank you for your great work and sharing the implementation of AlphaRec and datasets used in experiment section.

For the uploaded Amazon Book dataset, #items in train/valid/test sets in total is ~45k while the reported number in the paper is ~26k. Could you please clarify this difference?

Thank you,

**Comment by trannhuthuat96** [comment]
Hello @LehengTHU  

Thank you for your great work and sharing the implementation of AlphaRec and datasets used in experiment section.

For the uploaded Amazon Book dataset, #items in train/valid/test sets in total is ~45k while the reported number in the paper is ~26k. Could you please clarify this difference?

Thank you,
