### ISSUE TITLE
textual data

### ISSUE THREAD

**Issue by wangyu0627** [LehengTHU/AlphaRec#5]
May I ask how your textual data was obtained, including the cue words, which would be useful for us to reproduce your paper in other scenarios?

**Comment by LehengTHU** [comment]
In our paper, we simply use the `item title` as the textual data. You can obtain the item titles through the metadata in the Amazon dataset. You can refer to the examples of `item title` in the appendix of our paper.

**Comment by ChernovAndrey** [comment]
Hello!
Thank you for your work!

Could you please provide the  original link to the Amazon dataset with textual data? There are several versions of the Amazon datasets, and I couldn’t find in the paper which version you used.

Thank you in advance!
